"""Radar sirketleri icin resmi ana site adayi. Kesif girdisidir; kaynak kaniti degildir."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from watchlist import coverage, normalize

HOMES = {
    # Sigorta / Emeklilik
    "Allianz Türkiye": "https://www.allianz.com.tr/",
    "Anadolu Sigorta": "https://www.anadolusigorta.com.tr/",
    "AXA Sigorta": "https://www.axasigorta.com.tr/",
    "Aksigorta": "https://www.aksigorta.com.tr/",
    "AgeSA": "https://www.agesa.com.tr/",
    "Türkiye Sigorta": "https://www.turkiyesigorta.com.tr/",
    "Türkiye Hayat Emeklilik": "https://www.turkiyehayatemeklilik.com.tr/",
    "Zurich Sigorta": "https://www.zurichsigorta.com.tr/",
    "HDI Sigorta": "https://www.hdisigorta.com.tr/",
    "Mapfre Sigorta": "https://www.mapfre.com.tr/",
    "Sompo Sigorta": "https://www.sompo.com.tr/",
    "Generali Sigorta": "https://generalisigorta.com.tr/",
    "BNP Paribas Cardif": "https://www.bnpparibascardif.com.tr/",
    "Garanti BBVA Emeklilik": "https://www.garantibbvaemeklilik.com.tr/",
    # Telekom
    "Vodafone Türkiye": "https://www.vodafone.com.tr/",
    "Türk Telekom": "https://www.turktelekom.com.tr/",
    "Ericsson Türkiye": "https://www.ericsson.com/en/careers",
    "Nokia Türkiye": "https://www.nokia.com/about-us/careers/",
    "Huawei Türkiye": "https://www.huawei.com/tr/",
    # Yazilim / SaaS
    "Oracle Türkiye": "https://www.oracle.com/tr/careers/",
    "IBM Türkiye": "https://www.ibm.com/tr-tr/careers",
    "sahibinden.com": "https://www.sahibinden.com/",
    "n11": "https://www.n11.com/",
    "Motiwe": "https://www.motiwe.com/",
    # Gaming
    "Gleam Games": "https://www.gleamgames.com/",
    "Magic Games": "https://www.magicgames.co/",
    "Fuse Games": "https://www.fusegames.com/",
    # Danismanlik
    "Deloitte": "https://www.deloitte.com/tr/tr/careers.html",
    "KPMG": "https://kpmg.com/tr/tr/home/careers.html",
    "McKinsey & Company": "https://www.mckinsey.com/careers",
    "Boston Consulting Group": "https://careers.bcg.com/",
    "Bain & Company": "https://www.bain.com/careers/",
    "Simon-Kucher": "https://www.simon-kucher.com/en/careers",
    "Mercer": "https://careers.marshmclennan.com/",
    "Korn Ferry": "https://www.kornferry.com/careers",
    "Oliver Wyman": "https://www.oliverwyman.com/careers.html",
    "Strategy&": "https://www.strategyand.pwc.com/gx/en/careers.html",
    # Otomotiv
    "Toyota Türkiye": "https://www.toyota.com.tr/",
    "Toyota Motor Manufacturing Türkiye": "https://www.toyotatr.com/",
    "Mercedes-Benz Türk": "https://www.mercedes-benz.com.tr/",
    "Mercedes-Benz Otomotiv": "https://www.mercedes-benz.com.tr/",
    "Borusan Otomotiv / BMW": "https://www.borusanotomotiv.com/",
    "Oyak Renault": "https://www.oyak-renault.com.tr/",
    "Stellantis Türkiye": "https://www.stellantis.com.tr/",
    "Hyundai Motor Türkiye": "https://www.hyundai.com/tr/",
    "Anadolu Isuzu": "https://www.anadoluisuzu.com.tr/",
    "Karsan": "https://www.karsan.com/",
    "TEMSA": "https://www.temsa.com/",
    "MAN Türkiye": "https://www.man.com.tr/",
    "Scania / Doğuş Otomotiv": "https://www.scania.com.tr/",
    "Doğuş Otomotiv": "https://www.dogusotomotiv.com.tr/",
    "Continental Türkiye": "https://www.continental.com.tr/",
    "Magna": "https://www.magna.com/careers",
    "Autoliv Türkiye": "https://www.autoliv.com/careers",
    "Farplas": "https://www.farplas.com/",
    "Martur Fompak": "https://www.marturfompak.com/",
    "Coşkunöz": "https://www.coskunoz.com.tr/",
    "Maxion İnci": "https://www.maxionwheels.com/",
    "İnci GS Yuasa": "https://www.incigsyuasa.com/",
    "Prometeon Türkiye": "https://www.prometeon.com.tr/",
    "Brisa": "https://www.brisa.com.tr/",
    # Havacilik
    "Turkish Airlines": "https://careers.turkishairlines.com/",
    "Turkish Technic": "https://www.turkishtechnic.com/",
    "Pegasus": "https://www.flypgs.com/",
    "TAV Havalimanları": "https://www.tav.aero/",
    "İGA İstanbul Airport": "https://www.igairport.aero/",
    "ISG / Sabiha Gökçen": "https://www.sabihagokcen.aero/",
    "TEI": "https://www.tei.com.tr/",
    "Alp Aviation": "https://www.alp.com.tr/",
    # Savunma
    "ASELSAN": "https://www.aselsan.com/",
    "HAVELSAN": "https://www.havelsan.com.tr/",
    "ROKETSAN": "https://www.roketsan.com.tr/",
    "STM": "https://www.stm.com.tr/",
    "FNSS": "https://kariyer.fnss.com.tr/",
    # Buyuk sanayi / holding
    "Sabancı Holding": "https://www.sabanci.com/tr/",
    "Borusan Holding": "https://www.borusan.com/",
    "Eczacıbaşı Holding": "https://www.eczacibasi.com.tr/",
    "Zorlu Holding": "https://www.zorlu.com.tr/",
    "Anadolu Grubu": "https://www.anadolugrubu.com.tr/",
    "Akkök Holding": "https://www.akkok.com.tr/",
    "Kibar Holding": "https://www.kibar.com/",
    "Yaşar Holding": "https://www.yasar.com.tr/",
    "Doğuş Grubu": "https://www.dogusgrubu.com.tr/",
    "Alarko Holding": "https://www.alarko.com.tr/",
    "Limak Holding": "https://www.limak.com.tr/",
    "Tekfen Holding": "https://www.tekfen.com.tr/",
    "Yıldız Holding": "https://www.yildizholding.com.tr/",
    "Çalık Holding": "https://www.calik.com/",
    "IC Holding": "https://icholding.com.tr/",
    "Rönesans Holding": "https://www.ronesans.com/",
    "Cengiz Holding": "https://www.cengizholding.com.tr/",
    "Kalyon Holding": "https://www.kalyonholding.com/",
    "Karadeniz Holding": "https://www.karadenizholding.com/",
    "Coşkunöz Holding": "https://www.coskunoz.com.tr/",
    "Borusan Mannesmann": "https://www.borusanmannesmann.com/",
    "Şişecam": "https://www.sisecam.com.tr/",
    "Kordsa": "https://www.kordsa.com/",
    "Akçansa": "https://www.akcansa.com.tr/",
    "Çimsa": "https://www.cimsa.com.tr/",
    "Limak Çimento": "https://www.limakcimento.com/",
    "OYAK": "https://www.oyak.com.tr/",
    "Assan Alüminyum": "https://www.assanaluminyum.com/",
    "ASAŞ": "https://www.asas.com.tr/",
    "Kastamonu Entegre": "https://www.keas.com.tr/",
    "Kaleseramik": "https://www.kale.com.tr/",
    "Kalekim": "https://www.kalekim.com.tr/",
    "Eczacıbaşı VitrA": "https://www.vitra.com.tr/",
    "Akkim": "https://www.akkim.com.tr/",
    # Enerji
    "Tüpraş": "https://www.tupras.com.tr/",
    "SOCAR Türkiye": "https://www.socar.com.tr/",
    "Petkim": "https://www.petkim.com.tr/",
    "Enerjisa Enerji": "https://www.enerjisa.com.tr/",
    "Enerjisa Üretim": "https://www.enerjisauretim.com/",
    "Aksa Enerji": "https://www.aksaenerji.com.tr/",
    "Aydem Enerji": "https://www.aydemenerji.com.tr/",
    "Zorlu Enerji": "https://www.zorluenerji.com.tr/",
    "YEO Teknoloji": "https://www.yeo.com.tr/",
    "Eksim Holding": "https://www.eksim.com.tr/",
    "Shell Türkiye": "https://www.shell.com.tr/",
    "TotalEnergies Türkiye": "https://totalenergies.com.tr/",
    "Petrol Ofisi": "https://www.petrolofisi.com.tr/",
    "Opet": "https://www.opet.com.tr/",
    "BP Türkiye": "https://www.bp.com/tr_tr/turkey/home.html",
    "Borusan EnBW Enerji": "https://www.borusanenbw.com/",
    "Siemens Energy Türkiye": "https://www.siemens-energy.com/tr/tr.html",
    "Schneider Electric Türkiye": "https://www.se.com/tr/tr/",
    "Sanko Enerji": "https://www.sankoenerji.com.tr/",
    "Kalyon Enerji": "https://www.kalyonenerji.com.tr/",
    "Limak Enerji": "https://www.limakenerji.com.tr/",
    "GAMA Enerji": "https://www.gamaenerji.com/",
    "CK Enerji": "https://www.cenkenerji.com.tr/",
    # Perakende
    "LC Waikiki": "https://www.lcwaikiki.com/",
    "DeFacto": "https://www.defacto.com.tr/",
    "Boyner": "https://www.boynergrup.com/",
    "Beymen": "https://www.beymen.com/",
    "Migros": "https://www.migroskurumsal.com/",
    "CarrefourSA": "https://www.carrefoursa.com/",
    "BİM": "https://www.bim.com.tr/",
    "A101": "https://www.a101.com.tr/",
    "ŞOK Marketler": "https://www.sokmarket.com.tr/",
    "MediaMarkt": "https://www.mediamarkt.com.tr/",
    "Teknosa": "https://www.teknosa.com/",
    "IKEA Türkiye": "https://www.ikea.com.tr/",
    "Decathlon Türkiye": "https://www.decathlon.com.tr/",
    "ebebek": "https://www.ebebek.com/",
    "FLO": "https://www.flo.com.tr/",
    "Mavi": "https://www.mavi.com/",
    "Koton": "https://www.koton.com/",
    "Penti": "https://www.penti.com/",
    "English Home": "https://www.englishhome.com/",
    "Madame Coco": "https://www.madamecoco.com/",
    "Gratis": "https://www.gratis.com/",
    "Watsons": "https://www.watsons.com.tr/",
    # Lojistik
    "DHL": "https://careers.dhl.com/global/en",
    "DHL Supply Chain": "https://careers.dhl.com/global/en",
    "UPS Türkiye": "https://www.ups.com/tr/tr/Home.page",
    "FedEx Türkiye": "https://www.fedex.com/tr-tr/home.html",
    "CEVA Logistics": "https://www.cevalogistics.com/",
    "Mars Logistics": "https://www.marslogistics.com/",
    "Borusan Lojistik": "https://www.borusantedarik.com/",
    "Barsan": "https://www.barsan.com/",
    "Netlog Logistics": "https://www.netlog.com.tr/",
    "Ekol Logistics": "https://www.ekol.com/",
    "Arkas": "https://www.arkas.com.tr/",
    "Omsan Logistics": "https://www.omsan.com/",
    "Horoz Lojistik": "https://www.horoz.com.tr/",
    "DFDS Türkiye": "https://www.dfds.com/tr-tr",
    "Trendyol Express": "https://www.trendyolexpress.com/",
    "Hepsijet": "https://www.hepsijet.com/",
    # Elektronik / beyaz esya / endustriyel
    "Vestel": "https://www.vestel.com.tr/",
    "Siemens": "https://www.siemens.com/tr/tr.html",
    "Siemens Energy": "https://www.siemens-energy.com/global/en.html",
    "Schneider Electric": "https://www.se.com/ww/en/",
    "Honeywell": "https://www.honeywell.com/us/en/careers",
    "Mitsubishi Electric Türkiye": "https://tr.mitsubishielectric.com/tr/",
    "LG Electronics Türkiye": "https://www.lg.com/tr/",
    "Huawei": "https://www.huawei.com/en/",
    "Ericsson": "https://www.ericsson.com/en/careers",
    "Nokia": "https://www.nokia.com/about-us/careers/",
    "GE HealthCare Türkiye": "https://www.gehealthcare.com/about/careers",
    "Daikin Türkiye": "https://www.daikin.com.tr/",
    "Vaillant Türkiye": "https://www.vaillant.com.tr/",
    "Demirdöküm": "https://www.demirdokum.com.tr/",
}


def build():
    names = {r["name"] for r in coverage() if not r["url"]}
    seeds = [{"name": name, "home": home} for name, home in HOMES.items() if name in names]
    missing = sorted(names - set(HOMES))
    target = ROOT / ".source-audit" / "seeds.json"
    target.parent.mkdir(exist_ok=True)
    target.write_text(json.dumps(seeds, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(json.dumps({"seeds": len(seeds), "unmapped": len(missing)}, ensure_ascii=True))
    for name in missing:
        print("UNMAPPED:", name)


if __name__ == "__main__":
    build()
